import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from "next";
import "./globals.css";
import '@fontsource/prompt/500.css';

export const metadata: Metadata = {
  title: "NextCatflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}