import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from "next";
import "./globals.css";
import { TITLE } from "@/lib/constants";

export const metadata: Metadata = {
  title: TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}